name: calme
channels:
  - defaults
dependencies:
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - libcxx=10.0.0=1
  - libedit=3.1.20191231
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1g
  - pip=20.2.1=py37_0
  - python=3.7.7
  - readline=8.0
  - setuptools=49.2.1
  - sqlite=3.32.3
  - tk=8.6.10
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - chardet==3.0.4
    - idna==2.10
    - pyjwt==1.7.1
    - pytz==2020.1
    - requests==2.24.0
    - six==1.15.0
    - twilio==6.44.2
    - urllib3==1.25.10

